# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/pi/cyphal-types/voltbro/config/six_step/pid_report.1.0.dsdl
#
# Generated at:  2024-03-29 15:42:04.257373 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     voltbro.config.six_step.pid_report
# Version:       1.0
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import uavcan.primitive.scalar

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class pid_report_1_0:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 integral_error: None | uavcan.primitive.scalar.Real64_1_0 = None,
                 signal:         None | uavcan.primitive.scalar.Real64_1_0 = None) -> None:
        """
        voltbro.config.six_step.pid_report.1.0
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param integral_error: uavcan.primitive.scalar.Real64.1.0 integral_error
        :param signal:         uavcan.primitive.scalar.Real64.1.0 signal
        """
        self._integral_error: uavcan.primitive.scalar.Real64_1_0
        self._signal:         uavcan.primitive.scalar.Real64_1_0

        if integral_error is None:
            self.integral_error = uavcan.primitive.scalar.Real64_1_0()
        elif isinstance(integral_error, uavcan.primitive.scalar.Real64_1_0):
            self.integral_error = integral_error
        else:
            raise ValueError(f'integral_error: expected uavcan.primitive.scalar.Real64_1_0 '
                             f'got {type(integral_error).__name__}')

        if signal is None:
            self.signal = uavcan.primitive.scalar.Real64_1_0()
        elif isinstance(signal, uavcan.primitive.scalar.Real64_1_0):
            self.signal = signal
        else:
            raise ValueError(f'signal: expected uavcan.primitive.scalar.Real64_1_0 '
                             f'got {type(signal).__name__}')

    @property
    def integral_error(self) -> uavcan.primitive.scalar.Real64_1_0:
        """
        uavcan.primitive.scalar.Real64.1.0 integral_error
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._integral_error

    @integral_error.setter
    def integral_error(self, x: uavcan.primitive.scalar.Real64_1_0) -> None:
        if isinstance(x, uavcan.primitive.scalar.Real64_1_0):
            self._integral_error = x
        else:
            raise ValueError(f'integral_error: expected uavcan.primitive.scalar.Real64_1_0 got {type(x).__name__}')

    @property
    def signal(self) -> uavcan.primitive.scalar.Real64_1_0:
        """
        uavcan.primitive.scalar.Real64.1.0 signal
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._signal

    @signal.setter
    def signal(self, x: uavcan.primitive.scalar.Real64_1_0) -> None:
        if isinstance(x, uavcan.primitive.scalar.Real64_1_0):
            self._signal = x
        else:
            raise ValueError(f'signal: expected uavcan.primitive.scalar.Real64_1_0 got {type(x).__name__}')

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Serializer_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.pad_to_alignment(8)
        self.integral_error._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.signal._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        assert 128 <= (_ser_.current_bit_length - _base_offset_) <= 128, \
            'Bad serialization of voltbro.config.six_step.pid_report.1.0'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Deserializer_) -> pid_report_1_0:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "integral_error"
        _des_.pad_to_alignment(8)
        _f0_ = uavcan.primitive.scalar.Real64_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f1_ holds the value of "signal"
        _des_.pad_to_alignment(8)
        _f1_ = uavcan.primitive.scalar.Real64_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        self = pid_report_1_0(
            integral_error=_f0_,
            signal=_f1_)
        _des_.pad_to_alignment(8)
        assert 128 <= (_des_.consumed_bit_length - _base_offset_) <= 128, \
            'Bad deserialization of voltbro.config.six_step.pid_report.1.0'
        assert isinstance(self, pid_report_1_0)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'integral_error=%s' % self.integral_error,
            'signal=%s' % self.signal,
        ])
        return f'voltbro.config.six_step.pid_report.1.0({_o_0_})'

    _EXTENT_BYTES_ = 16

    # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
    # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
    # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
    # is not dependent on PyDSDL.
    _MODEL_: _pydsdl_.DelimitedType = _restore_constant_(
        'ABzY8OyLG*0{?|oYj4y>6y3Ctgf}RKwyIQ?exQMZJ05%NF;&|XS|qv<qEI5#idtiPvUjN0cKwKUD<Opst%zi)NKC)?r}oY|j|~tt'
        'QsnX6nRD+wKIiWCv46f^>`njL%f%$AlGF+-St^mLKSY#DD~$6|kyomgx;^u~Ow|aN$xo9)>eu?(3;kR#xAUROGFfWqwPzmHWfRv;'
        'DGwhx9%f>M5T9-3X&sfh73bNe8d{YahgB^Lt58W;$|5go-7bb(vaD2|8N`K+-Suldm>cx|(l2y-Din2Hs;H@DrJo}F5w-81((UoP'
        'N~Xy{K_|mR)FP}+m9Wrl!pZj2Mr_3*vx?F*s<xz6#Ud4@wJt^Kxf)Kx*}XF0!cz?wcdveQR1Nz`x;=3>%|(5fm{Vb->M)hrum(L?'
        '!Mb8m)!`^lu&yiZrM125=9+Z}V-HLS$>{y5*LC{=(kHS+l*ug6OT-z8VW#RPF^M-z5!Xm!h2-AdT_eU5HrMOfe&Bn7V>>SQsADsq'
        'aNA|ncd6q$wohD#d49l&Pw>eo<E|S79t(J2`>yYCV(w6n_?!^RnZtdLFdi_*J%{?9$9-=5Hgkz<b{%HB4yUe%@UBB`hkBd`_-b=J'
        '%w0@@|HNUA&ulN?9>HujVZO(hO*tjLM_uLygapLlfkW}KOMFbm8R0G-a-0CMO*V%*9-g9<1}?Wf#tCOEa4;)%uv=^qTj$iH#I;@5'
        '$L6tE2dnjMP69iiLBP398Nu2K^=$6i)a8ilac#(NB2>)rEs-|J@v$(;W8IP;#z=2E>7$rSS;?$6GU%(UmO~Wst^O}J>GkW(xzYb('
        '`h1EgqFtI1bQn!Kvpm<}!sQAjk{GO5pz-uhdp6uuW0{1;E1^pCYI`B9@}`U>22vRo0tL`6m`AE2{P=5V-|?E+eT{;f`x0w~+?esb'
        'Lh1H&JSjk=H;ofe9-kCVl&ToLIBZgr@xUh-o$u^{pfj?b?<}I*bDc>n+ai{+g0781mqHK~R#hSw#v5BImU;(R+cTs^DZ*aev(ABp'
        '@nrqxI~IFe)%U0GkMMQZMD6=wUg)-e6i780MLG6_r96<M9F1w@|FDpysPl4mjK!dEM!=)?+?q%dl?~rI1W!zKwMntz$(vC`=)~~1'
        'ULLHxsv?|ZMF*q@i%o>>j#Oq`jten1iv{C!B--3Q8Om`Xvgxo}ZK5ig>g()OI;BWMS(ca!7z{A5KX>3`JTzaaVJ6bupakE96kLK7'
        'o;48cz^zsI3cgu}Z(#+#gWK)G?i|LNyGe|LVQ&^APY2WZ@W+H7cT5Vn4-cpLVI3at6Z7-_>hTO&7w_bmk#6=**4q;u=_n2}$lr;!'
        '0kL5ZlEDf{{NKd9fCRyYtjz8<?rtCK?j1h7-LVO$aDbmTgL@gtdG`NAK?XS#@cT^j_|4=P`>FL{yS;?o?0yr=5Tr=((fy=cX_p>n'
        '=Bvo$Ug!Nob04k_`tUhi8_bzO0ykb_b?+qgdAGG~D*m-w3nQ;S%Igr%AFhjRDA#2nYju>qf9qs-9xu#dExwwvlMH%$lnoZme(zN^'
        '<*uW-kHLT64w|dhe}2H%5l9FC00'
    )
    assert isinstance(_MODEL_, _pydsdl_.DelimitedType)
