# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/pi/cyphal-types/voltbro/config/six_step/pid_config.1.0.dsdl
#
# Generated at:  2024-03-29 15:42:04.243227 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     voltbro.config.six_step.pid_config
# Version:       1.0
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import uavcan.primitive.scalar

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class pid_config_1_0:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 p_gain:             None | uavcan.primitive.scalar.Real64_1_0 = None,
                 i_gain:             None | uavcan.primitive.scalar.Real64_1_0 = None,
                 d_gain:             None | uavcan.primitive.scalar.Real64_1_0 = None,
                 integral_error_lim: None | uavcan.primitive.scalar.Real64_1_0 = None,
                 tolerance:          None | uavcan.primitive.scalar.Real64_1_0 = None) -> None:
        """
        voltbro.config.six_step.pid_config.1.0
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param p_gain:             uavcan.primitive.scalar.Real64.1.0 p_gain
        :param i_gain:             uavcan.primitive.scalar.Real64.1.0 i_gain
        :param d_gain:             uavcan.primitive.scalar.Real64.1.0 d_gain
        :param integral_error_lim: uavcan.primitive.scalar.Real64.1.0 integral_error_lim
        :param tolerance:          uavcan.primitive.scalar.Real64.1.0 tolerance
        """
        self._p_gain:             uavcan.primitive.scalar.Real64_1_0
        self._i_gain:             uavcan.primitive.scalar.Real64_1_0
        self._d_gain:             uavcan.primitive.scalar.Real64_1_0
        self._integral_error_lim: uavcan.primitive.scalar.Real64_1_0
        self._tolerance:          uavcan.primitive.scalar.Real64_1_0

        if p_gain is None:
            self.p_gain = uavcan.primitive.scalar.Real64_1_0()
        elif isinstance(p_gain, uavcan.primitive.scalar.Real64_1_0):
            self.p_gain = p_gain
        else:
            raise ValueError(f'p_gain: expected uavcan.primitive.scalar.Real64_1_0 '
                             f'got {type(p_gain).__name__}')

        if i_gain is None:
            self.i_gain = uavcan.primitive.scalar.Real64_1_0()
        elif isinstance(i_gain, uavcan.primitive.scalar.Real64_1_0):
            self.i_gain = i_gain
        else:
            raise ValueError(f'i_gain: expected uavcan.primitive.scalar.Real64_1_0 '
                             f'got {type(i_gain).__name__}')

        if d_gain is None:
            self.d_gain = uavcan.primitive.scalar.Real64_1_0()
        elif isinstance(d_gain, uavcan.primitive.scalar.Real64_1_0):
            self.d_gain = d_gain
        else:
            raise ValueError(f'd_gain: expected uavcan.primitive.scalar.Real64_1_0 '
                             f'got {type(d_gain).__name__}')

        if integral_error_lim is None:
            self.integral_error_lim = uavcan.primitive.scalar.Real64_1_0()
        elif isinstance(integral_error_lim, uavcan.primitive.scalar.Real64_1_0):
            self.integral_error_lim = integral_error_lim
        else:
            raise ValueError(f'integral_error_lim: expected uavcan.primitive.scalar.Real64_1_0 '
                             f'got {type(integral_error_lim).__name__}')

        if tolerance is None:
            self.tolerance = uavcan.primitive.scalar.Real64_1_0()
        elif isinstance(tolerance, uavcan.primitive.scalar.Real64_1_0):
            self.tolerance = tolerance
        else:
            raise ValueError(f'tolerance: expected uavcan.primitive.scalar.Real64_1_0 '
                             f'got {type(tolerance).__name__}')

    @property
    def p_gain(self) -> uavcan.primitive.scalar.Real64_1_0:
        """
        uavcan.primitive.scalar.Real64.1.0 p_gain
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._p_gain

    @p_gain.setter
    def p_gain(self, x: uavcan.primitive.scalar.Real64_1_0) -> None:
        if isinstance(x, uavcan.primitive.scalar.Real64_1_0):
            self._p_gain = x
        else:
            raise ValueError(f'p_gain: expected uavcan.primitive.scalar.Real64_1_0 got {type(x).__name__}')

    @property
    def i_gain(self) -> uavcan.primitive.scalar.Real64_1_0:
        """
        uavcan.primitive.scalar.Real64.1.0 i_gain
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._i_gain

    @i_gain.setter
    def i_gain(self, x: uavcan.primitive.scalar.Real64_1_0) -> None:
        if isinstance(x, uavcan.primitive.scalar.Real64_1_0):
            self._i_gain = x
        else:
            raise ValueError(f'i_gain: expected uavcan.primitive.scalar.Real64_1_0 got {type(x).__name__}')

    @property
    def d_gain(self) -> uavcan.primitive.scalar.Real64_1_0:
        """
        uavcan.primitive.scalar.Real64.1.0 d_gain
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._d_gain

    @d_gain.setter
    def d_gain(self, x: uavcan.primitive.scalar.Real64_1_0) -> None:
        if isinstance(x, uavcan.primitive.scalar.Real64_1_0):
            self._d_gain = x
        else:
            raise ValueError(f'd_gain: expected uavcan.primitive.scalar.Real64_1_0 got {type(x).__name__}')

    @property
    def integral_error_lim(self) -> uavcan.primitive.scalar.Real64_1_0:
        """
        uavcan.primitive.scalar.Real64.1.0 integral_error_lim
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._integral_error_lim

    @integral_error_lim.setter
    def integral_error_lim(self, x: uavcan.primitive.scalar.Real64_1_0) -> None:
        if isinstance(x, uavcan.primitive.scalar.Real64_1_0):
            self._integral_error_lim = x
        else:
            raise ValueError(f'integral_error_lim: expected uavcan.primitive.scalar.Real64_1_0 got {type(x).__name__}')

    @property
    def tolerance(self) -> uavcan.primitive.scalar.Real64_1_0:
        """
        uavcan.primitive.scalar.Real64.1.0 tolerance
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._tolerance

    @tolerance.setter
    def tolerance(self, x: uavcan.primitive.scalar.Real64_1_0) -> None:
        if isinstance(x, uavcan.primitive.scalar.Real64_1_0):
            self._tolerance = x
        else:
            raise ValueError(f'tolerance: expected uavcan.primitive.scalar.Real64_1_0 got {type(x).__name__}')

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Serializer_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.pad_to_alignment(8)
        self.p_gain._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.i_gain._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.d_gain._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.integral_error_lim._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.tolerance._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        assert 320 <= (_ser_.current_bit_length - _base_offset_) <= 320, \
            'Bad serialization of voltbro.config.six_step.pid_config.1.0'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Deserializer_) -> pid_config_1_0:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "p_gain"
        _des_.pad_to_alignment(8)
        _f0_ = uavcan.primitive.scalar.Real64_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f1_ holds the value of "i_gain"
        _des_.pad_to_alignment(8)
        _f1_ = uavcan.primitive.scalar.Real64_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f2_ holds the value of "d_gain"
        _des_.pad_to_alignment(8)
        _f2_ = uavcan.primitive.scalar.Real64_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f3_ holds the value of "integral_error_lim"
        _des_.pad_to_alignment(8)
        _f3_ = uavcan.primitive.scalar.Real64_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f4_ holds the value of "tolerance"
        _des_.pad_to_alignment(8)
        _f4_ = uavcan.primitive.scalar.Real64_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        self = pid_config_1_0(
            p_gain=_f0_,
            i_gain=_f1_,
            d_gain=_f2_,
            integral_error_lim=_f3_,
            tolerance=_f4_)
        _des_.pad_to_alignment(8)
        assert 320 <= (_des_.consumed_bit_length - _base_offset_) <= 320, \
            'Bad deserialization of voltbro.config.six_step.pid_config.1.0'
        assert isinstance(self, pid_config_1_0)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'p_gain=%s' % self.p_gain,
            'i_gain=%s' % self.i_gain,
            'd_gain=%s' % self.d_gain,
            'integral_error_lim=%s' % self.integral_error_lim,
            'tolerance=%s' % self.tolerance,
        ])
        return f'voltbro.config.six_step.pid_config.1.0({_o_0_})'

    _EXTENT_BYTES_ = 40

    # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
    # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
    # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
    # is not dependent on PyDSDL.
    _MODEL_: _pydsdl_.DelimitedType = _restore_constant_(
        'ABzY8OyLG*0{^{MTaOe)6rNSs3s(_Ajfo6C;DXTht-7l*(G`>g2bRquglMp=?yj9v*wfwV%Q{0s0uK^4=|mFB|HG^Q%2U&`v$M-C'
        '#uq1<>FRT<Q|El&sd;+nufLZ%<4<!gAH`*y7_1b9<cWOD!$cS?$_9B>%1Wr__;(_a16;;Gj&h-1sf*9l6SdsTGnuBMP|#_P->r%|'
        's_H`QHaW~vKEM#4ZDvUo7MT%c>4xkZr5v)d61kDfn6)z1EV4~elrl?o#D)8l^()nz>vf*1XR0~McvTfLtSeEfhZz2V+^1HmIebHk'
        'B;HBr2#a~eS*5dtg;oehnon!K8S&J}3w=<zDU34W2``Lw!4uC_a12gtrvaxPDmXK7{pg?^rjb;$bR)@lwYxA!Stu)(h_qjU>aAd2'
        '5ict?$YRXvd~<ef+g-aE*HL#{tFRcIKh(NvKEU$vH0DJ-8|Veb8Ss88t2)*jZxlSLu!toV_r_$6F&>b)PRH^C-wPbeaj9oJ7V%AL'
        'xy1He+wmRCH(iH#en3s%#3!){b=@HFNI(P2cYTkV+Q;@xpPHski9>zQBs3s|dXDXT9`&i^Tf{Y8Ep>?HI@ESO4DUL&<=7sj0lr!k'
        'jj4-U;Ma7B;}gpZsAuACmPve%5X+{v>3g<I+`u#g)1iT5qqA%JxEUoTb<xOi0*tM9b8N>$E8DgMms%d7CM6_ra97*G)8Y~F=+yRX'
        ')3sdJ$HQZ?4rc3H)C{b^4gyLoo0yopX?qrRE!(9S*P}`ozYY;Ghc|grV~r27IEz$cem}(WCZld4@<Nm%tuzd}GOa`(fqb?5^A-Ej'
        'CE{G}eldPN#3;NuJp*VKj#{!jQQ*S45+M@nSP@6!sjcP&+mJ&Mvpg#*CS$eQoML5G7m+|kB3RB50L_AaBr?S2uOWShYg+mW0XO$0'
        '<_ei6<2$)j&9P{d15d7KCLlaM$?GtY5i3N$PV|mDJVEVzOAib>1MB&gBC0vrlEknK)6i5<l}6}k2E4?q3ao|Z#-@yf+5*yabkV{D'
        '!(P~?&JKjpvfBHO$zGGyt?~O^e4UV}d6#9mYPtsnDMy1a!!uzjx5XesVrux`$wk4dte72R5lEa7aJM<R#^YF~{Wpx@f!40p2_AT~'
        'SBnu^F#M^Odn+%?5GPsQ22#DnI>h4+WU5(?3qI6~1<iCUwDvy2#4zXSc-XDhVHu9`HJ`ISM=v1IL&0?3z{grC-=>V;qI`dh$bu(K'
        '6h&4r9PIlWE>&5A$4s$ltzLkywGz%k0*@er0Thr!4P_0%7F=D0ui)!t_y$(sTe#LNOeQ{7XFA`vr#^OMXYTKY4g9dBw}V@7XPgeK'
        '!@X$>ewwcC&9vpr^(@sSN%!q<v(&a1VW_W+e~I?I-E`~!w7d_IMhV2d6%hE{Kx054z<p6_=~I+G-H~n^?-5UoU!(N(o5p*@t?}*7'
        '90>ih*ZfVz#9>9tSN3t(t7t(CNAcc#Pv4izh?+-;m>kOgh9meLhA@K1GuS}#h#|JSQn+Jt7N=zU@1$TLc#MzsazEdkzK5jhry{=D'
        'PT^fQFkI+$;d8jyo6{p5F2BHp_XXW-`+jNHTob*EMBjzO57&9x7waMyl{{$D{MHTt?Jyf_@#VN+aj!EiV{cI_Ixov{J=^AXQTyvY'
        'TJ3E712EyfIn)UN00'
    )
    assert isinstance(_MODEL_, _pydsdl_.DelimitedType)
