# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/pi/cyphal-types/voltbro/hmi/led_service.1.0.dsdl
#
# Generated at:  2024-03-29 15:42:04.087878 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     voltbro.hmi.led_service
# Version:       1.0
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import uavcan.primitive.scalar
import uavcan.si.unit.duration
import uavcan.si.unit.frequency

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class led_service_1_0:
    # noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
    class Request:
        """
        Generated property settings use relaxed type signatures, accepting a large variety of
        possible representations of the value, which are automatically converted to a well-defined
        internal representation. When accessing a property, this strict well-defined internal
        representation is always returned. The implicit strictification enables more precise static
        type analysis.

        The value returned by the __repr__() method may be invariant to some of the field values,
        and its format is not guaranteed to be stable. Therefore, the returned string representation
        can be used only for displaying purposes; any kind of automation build on top of that will
        be fragile and prone to mismaintenance.
        """
        def __init__(self,
                     r:         None | uavcan.primitive.scalar.Natural8_1_0 = None,
                     g:         None | uavcan.primitive.scalar.Natural8_1_0 = None,
                     b:         None | uavcan.primitive.scalar.Natural8_1_0 = None,
                     duration:  None | uavcan.si.unit.duration.Scalar_1_0 = None,
                     frequency: None | uavcan.si.unit.frequency.Scalar_1_0 = None,
                     interface: None | uavcan.primitive.scalar.Integer8_1_0 = None) -> None:
            """
            voltbro.hmi.led_service.Request.1.0
            Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
            :param r:         uavcan.primitive.scalar.Natural8.1.0 r
            :param g:         uavcan.primitive.scalar.Natural8.1.0 g
            :param b:         uavcan.primitive.scalar.Natural8.1.0 b
            :param duration:  uavcan.si.unit.duration.Scalar.1.0 duration
            :param frequency: uavcan.si.unit.frequency.Scalar.1.0 frequency
            :param interface: uavcan.primitive.scalar.Integer8.1.0 interface
            """
            self._r:         uavcan.primitive.scalar.Natural8_1_0
            self._g:         uavcan.primitive.scalar.Natural8_1_0
            self._b:         uavcan.primitive.scalar.Natural8_1_0
            self._duration:  uavcan.si.unit.duration.Scalar_1_0
            self._frequency: uavcan.si.unit.frequency.Scalar_1_0
            self._interface: uavcan.primitive.scalar.Integer8_1_0

            if r is None:
                self.r = uavcan.primitive.scalar.Natural8_1_0()
            elif isinstance(r, uavcan.primitive.scalar.Natural8_1_0):
                self.r = r
            else:
                raise ValueError(f'r: expected uavcan.primitive.scalar.Natural8_1_0 '
                                 f'got {type(r).__name__}')

            if g is None:
                self.g = uavcan.primitive.scalar.Natural8_1_0()
            elif isinstance(g, uavcan.primitive.scalar.Natural8_1_0):
                self.g = g
            else:
                raise ValueError(f'g: expected uavcan.primitive.scalar.Natural8_1_0 '
                                 f'got {type(g).__name__}')

            if b is None:
                self.b = uavcan.primitive.scalar.Natural8_1_0()
            elif isinstance(b, uavcan.primitive.scalar.Natural8_1_0):
                self.b = b
            else:
                raise ValueError(f'b: expected uavcan.primitive.scalar.Natural8_1_0 '
                                 f'got {type(b).__name__}')

            if duration is None:
                self.duration = uavcan.si.unit.duration.Scalar_1_0()
            elif isinstance(duration, uavcan.si.unit.duration.Scalar_1_0):
                self.duration = duration
            else:
                raise ValueError(f'duration: expected uavcan.si.unit.duration.Scalar_1_0 '
                                 f'got {type(duration).__name__}')

            if frequency is None:
                self.frequency = uavcan.si.unit.frequency.Scalar_1_0()
            elif isinstance(frequency, uavcan.si.unit.frequency.Scalar_1_0):
                self.frequency = frequency
            else:
                raise ValueError(f'frequency: expected uavcan.si.unit.frequency.Scalar_1_0 '
                                 f'got {type(frequency).__name__}')

            if interface is None:
                self.interface = uavcan.primitive.scalar.Integer8_1_0()
            elif isinstance(interface, uavcan.primitive.scalar.Integer8_1_0):
                self.interface = interface
            else:
                raise ValueError(f'interface: expected uavcan.primitive.scalar.Integer8_1_0 '
                                 f'got {type(interface).__name__}')

        @property
        def r(self) -> uavcan.primitive.scalar.Natural8_1_0:
            """
            uavcan.primitive.scalar.Natural8.1.0 r
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._r

        @r.setter
        def r(self, x: uavcan.primitive.scalar.Natural8_1_0) -> None:
            if isinstance(x, uavcan.primitive.scalar.Natural8_1_0):
                self._r = x
            else:
                raise ValueError(f'r: expected uavcan.primitive.scalar.Natural8_1_0 got {type(x).__name__}')

        @property
        def g(self) -> uavcan.primitive.scalar.Natural8_1_0:
            """
            uavcan.primitive.scalar.Natural8.1.0 g
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._g

        @g.setter
        def g(self, x: uavcan.primitive.scalar.Natural8_1_0) -> None:
            if isinstance(x, uavcan.primitive.scalar.Natural8_1_0):
                self._g = x
            else:
                raise ValueError(f'g: expected uavcan.primitive.scalar.Natural8_1_0 got {type(x).__name__}')

        @property
        def b(self) -> uavcan.primitive.scalar.Natural8_1_0:
            """
            uavcan.primitive.scalar.Natural8.1.0 b
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._b

        @b.setter
        def b(self, x: uavcan.primitive.scalar.Natural8_1_0) -> None:
            if isinstance(x, uavcan.primitive.scalar.Natural8_1_0):
                self._b = x
            else:
                raise ValueError(f'b: expected uavcan.primitive.scalar.Natural8_1_0 got {type(x).__name__}')

        @property
        def duration(self) -> uavcan.si.unit.duration.Scalar_1_0:
            """
            uavcan.si.unit.duration.Scalar.1.0 duration
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._duration

        @duration.setter
        def duration(self, x: uavcan.si.unit.duration.Scalar_1_0) -> None:
            if isinstance(x, uavcan.si.unit.duration.Scalar_1_0):
                self._duration = x
            else:
                raise ValueError(f'duration: expected uavcan.si.unit.duration.Scalar_1_0 got {type(x).__name__}')

        @property
        def frequency(self) -> uavcan.si.unit.frequency.Scalar_1_0:
            """
            uavcan.si.unit.frequency.Scalar.1.0 frequency
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._frequency

        @frequency.setter
        def frequency(self, x: uavcan.si.unit.frequency.Scalar_1_0) -> None:
            if isinstance(x, uavcan.si.unit.frequency.Scalar_1_0):
                self._frequency = x
            else:
                raise ValueError(f'frequency: expected uavcan.si.unit.frequency.Scalar_1_0 got {type(x).__name__}')

        @property
        def interface(self) -> uavcan.primitive.scalar.Integer8_1_0:
            """
            uavcan.primitive.scalar.Integer8.1.0 interface
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._interface

        @interface.setter
        def interface(self, x: uavcan.primitive.scalar.Integer8_1_0) -> None:
            if isinstance(x, uavcan.primitive.scalar.Integer8_1_0):
                self._interface = x
            else:
                raise ValueError(f'interface: expected uavcan.primitive.scalar.Integer8_1_0 got {type(x).__name__}')

        # noinspection PyProtectedMember
        def _serialize_(self, _ser_: _Serializer_) -> None:
            assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
            _base_offset_ = _ser_.current_bit_length
            _ser_.pad_to_alignment(8)
            self.r._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
            _ser_.pad_to_alignment(8)
            self.g._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
            _ser_.pad_to_alignment(8)
            self.b._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
            _ser_.pad_to_alignment(8)
            self.duration._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
            _ser_.pad_to_alignment(8)
            self.frequency._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
            _ser_.pad_to_alignment(8)
            self.interface._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
            _ser_.pad_to_alignment(8)
            assert 96 <= (_ser_.current_bit_length - _base_offset_) <= 96, \
                'Bad serialization of voltbro.hmi.led_service.Request.1.0'

        # noinspection PyProtectedMember
        @staticmethod
        def _deserialize_(_des_: _Deserializer_) -> led_service_1_0.Request:
            assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
            _base_offset_ = _des_.consumed_bit_length
            # Temporary _f0_ holds the value of "r"
            _des_.pad_to_alignment(8)
            _f0_ = uavcan.primitive.scalar.Natural8_1_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            # Temporary _f1_ holds the value of "g"
            _des_.pad_to_alignment(8)
            _f1_ = uavcan.primitive.scalar.Natural8_1_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            # Temporary _f2_ holds the value of "b"
            _des_.pad_to_alignment(8)
            _f2_ = uavcan.primitive.scalar.Natural8_1_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            # Temporary _f3_ holds the value of "duration"
            _des_.pad_to_alignment(8)
            _f3_ = uavcan.si.unit.duration.Scalar_1_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            # Temporary _f4_ holds the value of "frequency"
            _des_.pad_to_alignment(8)
            _f4_ = uavcan.si.unit.frequency.Scalar_1_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            # Temporary _f5_ holds the value of "interface"
            _des_.pad_to_alignment(8)
            _f5_ = uavcan.primitive.scalar.Integer8_1_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            self = led_service_1_0.Request(
                r=_f0_,
                g=_f1_,
                b=_f2_,
                duration=_f3_,
                frequency=_f4_,
                interface=_f5_)
            _des_.pad_to_alignment(8)
            assert 96 <= (_des_.consumed_bit_length - _base_offset_) <= 96, \
                'Bad deserialization of voltbro.hmi.led_service.Request.1.0'
            assert isinstance(self, led_service_1_0.Request)
            return self

        def __repr__(self) -> str:
            _o_0_ = ', '.join([
                'r=%s' % self.r,
                'g=%s' % self.g,
                'b=%s' % self.b,
                'duration=%s' % self.duration,
                'frequency=%s' % self.frequency,
                'interface=%s' % self.interface,
            ])
            return f'voltbro.hmi.led_service.Request.1.0({_o_0_})'

        _EXTENT_BYTES_ = 12

        # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
        # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
        # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
        # is not dependent on PyDSDL.
        _MODEL_: _pydsdl_.StructureType = _restore_constant_(
            'ABzY8OyLG*0{_ic-*4PR5KcmVT+%`lrJxEB2|ToEQQiEwqz(@twIXVC<OoeEsUX^{?aj>!pY86hPr0B-6bY2TN+4yC5N|xfBTu~b'
            'kv{>6zlPbfFL$}CO9etA(kbhi@$Ag^eY5M&hrj<}VxaY>XOd<hgU}(82~I<PK)sMT#E<JqEV*JvKfk3!>Z??+d(DKI6La;EIW%*6'
            'ghaHC{+UJ`Do?}?)VUL~z-DT2pE-Bg!<0#7bcr;WkUWkI4Ct}@`TE3E1}g(!nMX#SBUCBDy;L!2b})BARi{x#kF0SP2AygqNI(@O'
            '%9aR2nGr_xY)TtGjhsaAI#;~G9O=`L3a3i3BO1B}#$dc%2%O(BFqywRT~x(sE~BSEj3lo`ELe{et1)pFp>xFJii9kxDKM21*635I'
            'NIed)##i-Ao9#sQHRm?^HmnPQ8TiuNHToivibeqyL3g5~)WgO`8Z=C?f?*QGzR?3F^{Afi!jX8*jG#jUbMUgnY66xB=2OK2bF5z='
            'dwd_+N@Af14@^~05gDh#XXpqSNht26$Lzn5dq$6Mq8|1)t@Q+Z8@z#gLu>^wlyIZZ`^^Msc-;~pjeaFby^#Avuv!}09Xs@(cQj)K'
            'lXhV_nlWSaRGS-T!I^g~14damrU_7qbqN-!w#dveT!m|hf)`@m%Wc9saABb8ea32UarIv7c?%zN!t`?_PK=%{N+O$eFUF>@k_}dm'
            'Q4R`q{C>g&Rk7&MK1zJxs7+YY7dB}S@Tk@o1QqM8rXhCR?Db-XjNNa|T&47#^l*ZbED_2m^|0MKkF26_LHF%q%&H2Jwr@`mwx7_b'
            'HDuM)lU_?OgTh#-aD6IpxM=OQ0=w65@66R}`CLivq!Cw6fP`5zoUM$+;;BO6kFSL>RcB@eUa!o;8*mw}9AW)+TEnC%&VnA_6V$hv'
            'k>1i;zQ)(|m8J6hqPw_MURhakmls`kdDUH5xH(^5aF@z%d3j-Fb#b{|o;P-sS_q6v=EqTxw?*MioQ!?=RKoRRaH?<v7Uy6I%CHP8'
            'a1&fTBvIGHwmsas-JsDIvKG&Z6W(qK5#E7Yt%l%TxO2+%#_8&V%z4ieJB!4^eak0&gw1c`?*aNg?oig*^eIft^f0j}?6Dj9&1aw@'
            '>H{Ahg8B#0jsO$t;0&@q!buUbZ~&iKV)H@`9R6nzcJES*Vc{*2AM5VZ^*pszcn2V~r5xJsW4jxu-{99mpjP26J=HGaUn{QE4Oa=_'
            'D)qs|aWAn){dS4WmN*BWz!VVJ0S|WJYw+P`_y&H5U(zSkt;h230X$FfivVx2?r(yg7LJ~!g*#nG=8L!E$lhSl6VF~fo*lh-L)g!V'
            'zsdGTw&|b$&&c%xreK{(Yn?>vWXIYL?lI@Vm(Y5tKe)&IMHcL$)$I@NG5?eWZ=-d)Ke)&II1AoI>u!JWS+kX*^A`p};8mjv000'
        )
        assert isinstance(_MODEL_, _pydsdl_.StructureType)

    # noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
    class Response:
        """
        Generated property settings use relaxed type signatures, accepting a large variety of
        possible representations of the value, which are automatically converted to a well-defined
        internal representation. When accessing a property, this strict well-defined internal
        representation is always returned. The implicit strictification enables more precise static
        type analysis.

        The value returned by the __repr__() method may be invariant to some of the field values,
        and its format is not guaranteed to be stable. Therefore, the returned string representation
        can be used only for displaying purposes; any kind of automation build on top of that will
        be fragile and prone to mismaintenance.
        """
        def __init__(self,
                     accepted: None | uavcan.primitive.scalar.Bit_1_0 = None) -> None:
            """
            voltbro.hmi.led_service.Response.1.0
            Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
            :param accepted: uavcan.primitive.scalar.Bit.1.0 accepted
            """
            self._accepted: uavcan.primitive.scalar.Bit_1_0

            if accepted is None:
                self.accepted = uavcan.primitive.scalar.Bit_1_0()
            elif isinstance(accepted, uavcan.primitive.scalar.Bit_1_0):
                self.accepted = accepted
            else:
                raise ValueError(f'accepted: expected uavcan.primitive.scalar.Bit_1_0 '
                                 f'got {type(accepted).__name__}')

        @property
        def accepted(self) -> uavcan.primitive.scalar.Bit_1_0:
            """
            uavcan.primitive.scalar.Bit.1.0 accepted
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._accepted

        @accepted.setter
        def accepted(self, x: uavcan.primitive.scalar.Bit_1_0) -> None:
            if isinstance(x, uavcan.primitive.scalar.Bit_1_0):
                self._accepted = x
            else:
                raise ValueError(f'accepted: expected uavcan.primitive.scalar.Bit_1_0 got {type(x).__name__}')

        # noinspection PyProtectedMember
        def _serialize_(self, _ser_: _Serializer_) -> None:
            assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
            _base_offset_ = _ser_.current_bit_length
            _ser_.pad_to_alignment(8)
            self.accepted._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
            _ser_.pad_to_alignment(8)
            assert 8 <= (_ser_.current_bit_length - _base_offset_) <= 8, \
                'Bad serialization of voltbro.hmi.led_service.Response.1.0'

        # noinspection PyProtectedMember
        @staticmethod
        def _deserialize_(_des_: _Deserializer_) -> led_service_1_0.Response:
            assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
            _base_offset_ = _des_.consumed_bit_length
            # Temporary _f6_ holds the value of "accepted"
            _des_.pad_to_alignment(8)
            _f6_ = uavcan.primitive.scalar.Bit_1_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            self = led_service_1_0.Response(
                accepted=_f6_)
            _des_.pad_to_alignment(8)
            assert 8 <= (_des_.consumed_bit_length - _base_offset_) <= 8, \
                'Bad deserialization of voltbro.hmi.led_service.Response.1.0'
            assert isinstance(self, led_service_1_0.Response)
            return self

        def __repr__(self) -> str:
            _o_0_ = ', '.join([
                'accepted=%s' % self.accepted,
            ])
            return f'voltbro.hmi.led_service.Response.1.0({_o_0_})'

        _EXTENT_BYTES_ = 1

        # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
        # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
        # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
        # is not dependent on PyDSDL.
        _MODEL_: _pydsdl_.StructureType = _restore_constant_(
            'ABzY8OyLG*0{?YWTWb_C7~R%xcYE<tDn3|2pQKef_5P?(u_$ZTrIo5^3CT?C7syOPl38|zf_+e22q-lEU%%|Vl@1J(%$J;;@0^qG'
            'bAR1jrT_Tbx|`WdCd6_hs1)BQlRP1*%C)k>@!&7-J5#2vH2i&6^KcqAPQr0m_f=BR9P4-5N;+m#0=Y;e&mvM=q&(T<R;$9|k~(Q~'
            'V}&XLRDA7VI6e)HnMUPjI0=4<Q0I(brQ<dnhKpE@7X@G45nN^yHj5;qjuICs!tCHDRQ*~>+bJy)ZA31dX!FFTR8o^{3m2dU3nL1!'
            'd>G)`aNp`h1jaB(d0Q#TX>nGRCBlRwk{3q~usx)eQtL>rGNg6O-)M~h;<n@^)^=kFrKtP}d%<5P*3lxPCYuK8l?;2Swy7-f<T;Y5'
            'H26v=8TG4E$`RHbcyb(I9d24=lW}c$N*&Ka&tD;5MF$Pi$~Ypj(DW<Bs?ww!3z8E}@ho49A1PSy3oVR5rxpL6VsA5Bcs8i$`K%Vf'
            'FQ;7%RBlGiZSZTlWKyKW@S{@36DN*fb$(z3f=+2TKQIHK(2nF`@*s(#2N#uCB|t4wGQ4o3NQEA3z&#XzNrb#R@@S$IE_CPT1N683'
            '`94mEUinKzX-w}$Ahw$`h5aCtU7jmUfWy$f)7(&}%*63|l7he_!j8Y%qFE-2qyH8`BUYQG#AdtatB5c#_IFrs%>1zouZtc4g+{$('
            '*lsQg9L53d#6c|v3Pp~)7YXlZTJ&#Jvt*X_vr?yN%5}6oDuzLU`xuHZuwr4e2T2pQ;L$ofh9~e8p84AF3Zp1^i7|!K*Z7Pr@cdT<'
            'gcq>gCl9aS^|;5~@#qa4MC$ONQHPKCe!`WXhwPGnd(<npe*^#k'
        )
        assert isinstance(_MODEL_, _pydsdl_.StructureType)

    def __repr__(self) -> str:
        return 'voltbro.hmi.led_service.1.0()'


    _MODEL_: _pydsdl_.ServiceType = _restore_constant_(
        'ABzY8OyLG*0{_id-A^1<6yL4DE>KzsQfZn9eJL32l#hiDekMinV`U|vO^xDkXXdi!lG&MY=FWy~LTpV`NN&<5Tod1X^HCpt^36x1'
        '{sAWbE1tVEyF2W5fY_Kw!f@x@bI<*q-|w6|mj`{{u8!oIKVr&n*rDxcMo0rj9Cn|W4%H0HtNC8YIF({}iw1RO(GMFwmB;dhhw?zq'
        'iV-8ApGP$023K~-iIFWHL>7;NF3*0$B{hsQRrefj2A&2rra9DBJF2+aW*kV0qEV+o$UIktE8I=S$FiI+=f0K?5sE=L511Ko8p>^q'
        'oq@jXB}M-lqmJD{Gi2C=lLT}jHo}mYj!4}iuI2}<#yG1}EwqS30<A(YBjV^1F2bc25E$E*Fp(^t%tFzQCB^thZpf-Gwcm9)t<vBm'
        'L&Jv2xZzN@%0ZTkh|wZQY|XO~<8^UmqZLRk(^heAT}>e|xv%7=6wewVC$3EbJ00jSGBL6KI&mUI&}Z15B}Gm~CK2N)9u2b*3v?ji'
        'CQOBh#-@HiEyAfSkHjTom+hlkz87$V*|H+WjL?e$i{gYs4WHm%qM-gb%#>nq1M6mgLs^e8xBM;K8$4A27knngMXTWhac(LBLMg8K'
        'k?AlCi>VqpYR8T|I6Dxlf<aSU4#dhxG1k&Xo7d(vrGVs$j&TD>h`0jk@>Y?_BhcU$vS2zG_eM*w4qfQTyWbJ*9md~pzHi}cBA9r_'
        '@O&wzvx0<;n(1Luh-97CJS+!}b^L)(1H!$aBm0110mIsavbelKY@4~&9w*pPvz5rfj2qpv7$H{ok(@0TABQG(kRJ!aGKx%0x5ivm'
        'Q8*y`YEV#Bg-ol}Lk8XViQ8<lN@Rv+vtaUpR8--(UEpw4*{d0Lv)A6~tLKxx3YiwUjB7Rurr6N7ViB{u3JZU5&G867(JOGHJPkAO'
        'BD{2n_-mw!K_l!1F}NELOGQR`i)+akmx-Ch(%gc+uvl7NUeuQsbbV<>pP#=ySDM!sOL}Q(etBhKsZ^Sis+F1y420D3TsujNz#MkQ'
        '0r(*-9Km7*N^pA?bXb9x;T3olUK1BWtm{6N9&X)AP>RcOiYJQ`R-1(gZ^GNngy20`Z!5jo9^H*6KUTs{qp<La(i1+#<hSwnGo0J$'
        'NY>f(6eXs*l-O;a->%g-hZJEC`A~<(zo51sXu$8EVD@|XE{j?C0v;$~6QB~l{Ld&%?~=`7=2s#)*7eitd2B258-Uan6Kd1PcABVP'
        ';O9)DUWYftSPR5cS6neoR}twd_Rz&}uV9y0Er?V>oCN|`zy=elK;aPp{0NWXH~1-f0&Y=A?gMz9;*9{mV(B|UR|<#cNnt&8WKOJl'
        'uKI$xPdt0YV0`rA7eZYl&WQF`yy@TnPtQt*Qc$6xvW}v4v}0{KcbOCCNwiM(I(M1BiJf({>b=fg<{x6`duYAa>)d7jHFn-X>rSup'
        'NwX?NyqyFz^zqcEy;r*I`)0gCHS1_slXjM0%j$K!5}e-V!*@K-p~UTO@O<3hM;Q&iH<Qoh_O9dO)HYXFlBe$Q{FxnIB$h>ebp=dA'
        'TviaTW<mTN{(wKv->`cc209(Za~T@8rJGGLU&IB4<iC=hQ+#hiZH9RTZS_+J*WOzyu~qeWM?Kc?5uK6ZQ5-<~2f>)p-cAhw00'
    )
    assert isinstance(_MODEL_, _pydsdl_.ServiceType)
