# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2024-03-29 15:42:04.029141 UTC
# Namespace:     voltbro.echo

from voltbro.echo.echo_msg_1_0 import echo_msg_1_0 as echo_msg_1_0
from voltbro.echo.echo_service_1_0 import echo_service_1_0 as echo_service_1_0

# Convenience aliases of the newest minor versions known at the time of code generation.
echo_msg_1 = echo_msg_1_0
echo_service_1 = echo_service_1_0
