# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2024-03-29 15:42:04.111660 UTC
# Namespace:     voltbro.config

# There are no data types in this namespace. There may be data types in nested namespaces.
