# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/pi/cyphal-types/voltbro/config/dc/set.1.0.dsdl
#
# Generated at:  2024-03-29 15:42:04.162185 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     voltbro.config.dc.set
# Version:       1.0
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import uavcan.primitive.scalar
import voltbro.config.dc

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class set_1_0:
    # noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
    class Request:
        """
        Generated property settings use relaxed type signatures, accepting a large variety of
        possible representations of the value, which are automatically converted to a well-defined
        internal representation. When accessing a property, this strict well-defined internal
        representation is always returned. The implicit strictification enables more precise static
        type analysis.

        The value returned by the __repr__() method may be invariant to some of the field values,
        and its format is not guaranteed to be stable. Therefore, the returned string representation
        can be used only for displaying purposes; any kind of automation build on top of that will
        be fragile and prone to mismaintenance.
        """
        def __init__(self,
                     new_config: None | voltbro.config.dc.pid_config_1_0 = None) -> None:
            """
            voltbro.config.dc.set.Request.1.0
            Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
            :param new_config: voltbro.config.dc.pid_config.1.0 new_config
            """
            self._new_config: voltbro.config.dc.pid_config_1_0

            if new_config is None:
                self.new_config = voltbro.config.dc.pid_config_1_0()
            elif isinstance(new_config, voltbro.config.dc.pid_config_1_0):
                self.new_config = new_config
            else:
                raise ValueError(f'new_config: expected voltbro.config.dc.pid_config_1_0 '
                                 f'got {type(new_config).__name__}')

        @property
        def new_config(self) -> voltbro.config.dc.pid_config_1_0:
            """
            voltbro.config.dc.pid_config.1.0 new_config
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._new_config

        @new_config.setter
        def new_config(self, x: voltbro.config.dc.pid_config_1_0) -> None:
            if isinstance(x, voltbro.config.dc.pid_config_1_0):
                self._new_config = x
            else:
                raise ValueError(f'new_config: expected voltbro.config.dc.pid_config_1_0 got {type(x).__name__}')

        # noinspection PyProtectedMember
        def _serialize_(self, _ser_: _Serializer_) -> None:
            assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
            _base_offset_ = _ser_.current_bit_length
            _ser_.pad_to_alignment(8)
            # Delimited serialization of voltbro.config.dc.pid_config.1.0, fixed bit length 192 (24 bytes)
            _ser_.add_aligned_u32(24)  # Delimiter header is constant in this case.
            _ser_base_offset_ = _ser_.current_bit_length
            self.new_config._serialize_(_ser_)
            assert _ser_.current_bit_length - _ser_base_offset_ == 192
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
            _ser_.pad_to_alignment(8)
            assert 32 <= (_ser_.current_bit_length - _base_offset_) <= 224, \
                'Bad serialization of voltbro.config.dc.set.Request.1.0'

        # noinspection PyProtectedMember
        @staticmethod
        def _deserialize_(_des_: _Deserializer_) -> set_1_0.Request:
            assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
            _base_offset_ = _des_.consumed_bit_length
            # Temporary _f0_ holds the value of "new_config"
            _des_.pad_to_alignment(8)
            # Delimited deserialization of voltbro.config.dc.pid_config.1.0, extent 192
            _dh_ = _des_.fetch_aligned_u32()  # Read the delimiter header.
            if _dh_ * 8 > _des_.remaining_bit_length:
                raise _des_.FormatError(f'Delimiter header specifies {_dh_ * 8} bits, '
                                        f'but the remaining length is only {_des_.remaining_bit_length} bits')
            _nested_ = _des_.fork_bytes(_dh_)
            _des_.skip_bits(_dh_ * 8)
            _f0_ = voltbro.config.dc.pid_config_1_0._deserialize_(_nested_)
            del _nested_
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            self = set_1_0.Request(
                new_config=_f0_)
            _des_.pad_to_alignment(8)
            assert 32 <= (_des_.consumed_bit_length - _base_offset_) <= 224, \
                'Bad deserialization of voltbro.config.dc.set.Request.1.0'
            assert isinstance(self, set_1_0.Request)
            return self

        def __repr__(self) -> str:
            _o_0_ = ', '.join([
                'new_config=%s' % self.new_config,
            ])
            return f'voltbro.config.dc.set.Request.1.0({_o_0_})'

        _EXTENT_BYTES_ = 28

        # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
        # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
        # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
        # is not dependent on PyDSDL.
        _MODEL_: _pydsdl_.StructureType = _restore_constant_(
            'ABzY8OyLG*0{_ic-EJF26m~-M+muoQ1*w#n8=45ZjUC5v5f!C@KrszbQb3|gC$qZ~pHauV+u7OFZj~wpiV|rgf-=4DqvS2P?F;Y('
            '+;GNg$A3u#cUZDKbIzG>&d+zwc<0QEzsE9-kDiL^e(Vc}#7uH3_+#n{<`6HeMq$hqGy2?`l8L7h$?n!8W)95EGqY``^$-bY74?_5'
            'LZMt4I$juT@`~eoPRx|E${r>xRz{DKEhb|g1_m;E<cH?^z?28dncvJaqt6nml;m!rSZvnKNiH2389lVbnef}Lj1!+KN|f~vFFE%G'
            '6TFJf``sQ76CMOi8W>CkFr?q>cRu1iNp}WDV65dPOswOHH<~9WJ22i)=$1zVCzAG3zQvr_qk>9I0TpxkK9n}dNueGg89lZnLaMss'
            'I7?ivh+siQfhlJ(e2>P8R6`%bpV1drTF31%XAyOGtO`?}d2UvXev8D420oR3C(th9RB0vPD)H^bo0578OBG`YmzrzD&{yUPv-whf'
            'u23w_mFDxM(){&OF1IjS$d%>_rNVr!cs)N~D9jprSK?xVhPJ3k5b_N1L(k~qmo-Ea^{ix(WHAerjXKK%#VW{-PqO!}=86jo3;A5}'
            '<LpPR<vL<fJ=wt(;?`3NZX5U%uEdxZ-y(VxD{uDn>tvJHm`|cmD#CrUtS^u_Or*z9AsC4$My*HekKiswyn>9ctyt*+W_jQmdJLhZ'
            '_+Z41p781sP;u3=40CcRN?gG`B3UI7_Qo~`Q9GP+0zo@!Ih^vs=<_KvoSZZ3*!mk~%Q8uT#^{yAj95Z!agUijxS=yPb*@0z4_ka`'
            '*Nxa_>)E5Tx48PYv0uY&lR5e|5=KU6PXdYSRX4<#(3Lx^8X_BQ&A*G7q$-r1edGbh{)2n^{0jAb9#r~_V8d#c6M+HOd$ov=QsQ?r'
            'UC!>uE)Iz(1v2H)#Kmx{Jh0Tp1+Ce|h^03s+MXUKtQOIrF-MjYH+CB=8?Pop@knsn;WuCnh3#(r01bvCQlSWYypo@$^iNT~*&wc@'
            'f-osVNpSQWZ#bqxfq4k9s;QpAXIA?Vra*y&N07i{sKGWofgO07z~_5#YZ(?{X&SzQui-X)qeq(a3RBpeQF_p~1#3^OZdSqSp1ln2'
            '!jBDS;3rr=s*roMTJNaZ+lygfdnh=z{CX^{KC;x<iFi8NAL*t4Q_K7Cz|svwISW<%251~1qu@S^t@I{JZ?>f^;~sI-cmt&y{l-1w'
            'rtuC+clwQc#7*OuD1F&)+#_xpAENZI-?&?xwhUatr|EL~uuUNW6C~dgc>3RI2|vRx@GCs;ARIO<t09M!DIe;KIGEEHSrTB>$Dj1A'
            'p3#%vV;@%n=HE`of7eR~4i@Da<jMo~ErG%=dVMUBI}5#;u6b*=baDHgRT@;-DvOxnCk?j;>CAZ-4|HOU?l-a~%9&Ow%cEAF*^e7J'
            'P1A3Q^r~Okno$9JboA$<F$1VgHv9z_;uG_#C+u|Y>FV8o)75`=@%vR*`JI0N;h*s21_}TG'
        )
        assert isinstance(_MODEL_, _pydsdl_.StructureType)

    # noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
    class Response:
        """
        Generated property settings use relaxed type signatures, accepting a large variety of
        possible representations of the value, which are automatically converted to a well-defined
        internal representation. When accessing a property, this strict well-defined internal
        representation is always returned. The implicit strictification enables more precise static
        type analysis.

        The value returned by the __repr__() method may be invariant to some of the field values,
        and its format is not guaranteed to be stable. Therefore, the returned string representation
        can be used only for displaying purposes; any kind of automation build on top of that will
        be fragile and prone to mismaintenance.
        """
        def __init__(self,
                     ok: None | uavcan.primitive.scalar.Bit_1_0 = None) -> None:
            """
            voltbro.config.dc.set.Response.1.0
            Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
            :param ok: uavcan.primitive.scalar.Bit.1.0 ok
            """
            self._ok: uavcan.primitive.scalar.Bit_1_0

            if ok is None:
                self.ok = uavcan.primitive.scalar.Bit_1_0()
            elif isinstance(ok, uavcan.primitive.scalar.Bit_1_0):
                self.ok = ok
            else:
                raise ValueError(f'ok: expected uavcan.primitive.scalar.Bit_1_0 '
                                 f'got {type(ok).__name__}')

        @property
        def ok(self) -> uavcan.primitive.scalar.Bit_1_0:
            """
            uavcan.primitive.scalar.Bit.1.0 ok
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._ok

        @ok.setter
        def ok(self, x: uavcan.primitive.scalar.Bit_1_0) -> None:
            if isinstance(x, uavcan.primitive.scalar.Bit_1_0):
                self._ok = x
            else:
                raise ValueError(f'ok: expected uavcan.primitive.scalar.Bit_1_0 got {type(x).__name__}')

        # noinspection PyProtectedMember
        def _serialize_(self, _ser_: _Serializer_) -> None:
            assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
            _base_offset_ = _ser_.current_bit_length
            _ser_.pad_to_alignment(8)
            self.ok._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
            _ser_.pad_to_alignment(8)
            assert 8 <= (_ser_.current_bit_length - _base_offset_) <= 8, \
                'Bad serialization of voltbro.config.dc.set.Response.1.0'

        # noinspection PyProtectedMember
        @staticmethod
        def _deserialize_(_des_: _Deserializer_) -> set_1_0.Response:
            assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
            _base_offset_ = _des_.consumed_bit_length
            # Temporary _f1_ holds the value of "ok"
            _des_.pad_to_alignment(8)
            _f1_ = uavcan.primitive.scalar.Bit_1_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            self = set_1_0.Response(
                ok=_f1_)
            _des_.pad_to_alignment(8)
            assert 8 <= (_des_.consumed_bit_length - _base_offset_) <= 8, \
                'Bad deserialization of voltbro.config.dc.set.Response.1.0'
            assert isinstance(self, set_1_0.Response)
            return self

        def __repr__(self) -> str:
            _o_0_ = ', '.join([
                'ok=%s' % self.ok,
            ])
            return f'voltbro.config.dc.set.Response.1.0({_o_0_})'

        _EXTENT_BYTES_ = 1

        # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
        # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
        # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
        # is not dependent on PyDSDL.
        _MODEL_: _pydsdl_.StructureType = _restore_constant_(
            'ABzY8OyLG*0{?YWU27CE6y4Ttw_kpgiVs%QC)p}Z{eD!aSd_Kv(n?jdgv=z}8_Z6IB(v-a1^b}55Kw6RzuxR@cWb2s!`#fhIXU;7'
            'n{P9J)J$dg_*;3OTdoMT!bqm%SC%M2XsSE8w$h2<FYY>1q^>aHT|XD$IIJCo!%+8Cnz0V%Z+5kEiP0q0*@0{mo)Rk@*%3C^nZ<%R'
            '+7-r1odu})+TJKW4vncs<wrOQevvZgj7$nAY}gOyaT*r|U)_>I@d=j&%9&%-MS?J0{)DPuEm${Y8Oe?8NGH33*pw+|$fk4wYA}C7'
            '0haayTp8_KIgh{?1}Sf9tpv;dm1L17(orR{wgYSrX{F3M+R+?o-SF31CjfC9d4aj@m_jKk-@{JuSE+R@<IM2WK!YN|UaDQD3Osp+'
            'a-9ZW2}Q#E$|>b&(k~r33{Z#b7TIu-8<8?6co_Ig^g#9mr@1zcN*<binOa?#RA530nln7h*WyRXB>4Fj4nVIJ{~lv+QyX|T=;-)#'
            'E`wi6`#CVR9yPbYujWOfWJ--_7b>1OaRjror4a~vO2gUG41_{E$OCepMA3tbN~};|7AYB#x#&VyrXmbr4ep`<i9*ObCmv0dqH*rd'
            'tV{Ga!}TsMM_&00ROi9pJ`cq9JBh}Akjb{_Xq*6tL;E%thB<8}j?dB*Bu*l1`O7WFxy;)C6+t6rn}xz=`)9L=P#XIy)EiU3ZGzV&'
            'FM&d1u1K)mj?6HO0qez}76%GNj=LAA=;bUM-l%4g*km{>)A~z@TH%PmJsgM6uxw#{0Hg^U@URY#;4wUbr@l72y2zruyyz{*o|mEq'
            '{}=+#envoe4x2;T@Dg5)yW1W|uVF8ehWCv*_<-+6to$_MMg9Vdmw9J*1ONa'
        )
        assert isinstance(_MODEL_, _pydsdl_.StructureType)

    def __repr__(self) -> str:
        return 'voltbro.config.dc.set.1.0()'


    _MODEL_: _pydsdl_.ServiceType = _restore_constant_(
        'ABzY8OyLG*0{_icZEq7t5O#P;OcJ0pg(A@xt3otY;fNi_ar%h{nzk~8H0i6_XxY14JR8n;$KIZaQBgw?ZCtHXB$i73P>G+y59tSf'
        'L)Gu?tj{lJJ5FgoHB!!dGqcal&O9@-JBOb9Hl1nxsW-!h8@ZlEA|^QX_+4sy%py)u3xkMDrq$F26Ls#ePa7fAkM%qE^*ueSjuOFc'
        '$1IXW8aZUt(G4kLN5*2n@-Xpf4RKzt2cEP=U^#(*lUFU*u_7j|^#n$%EU7aQ@xV7=6Q8%&k9B3NlKDa3M@I;iQgAz#EYh2Ll<Qq1'
        'tq!kn=D9srCW%WW?Rk8KdAx>)bo)IXC*1d$&@hn*U{bv{?0m>wlDuh{hGQK!;lw8HIN9ELI)(8@OzRHytx%Yc@;b93hk8_C2&gw-'
        '7((fRj5=x;Nvk6(UO;94Ii`rsCGnVFm7ps*JibFQVYR@;<6G*~T4%f2W?e?zHKW3iXCCTxtzIFKq`pgqn+DoNoEokAT*j{X@J&G-'
        'iK&V(g)8kfVyL(0i*to?VZK-@&6gJn<?_N(IiFvgE9T4d#d2{WUs@_G6pM4(d@HswK!@wpixKh=aRW!I(g)j!<~4GHg@Q%Qm*&(t'
        '?n_ohcD$GS`a-_6xVTuzm(J(j?JPGDi>jFvSBTw6D0ol9`*1$OxVQ$<p_qByRL96ozRg?`20{|<>Q!}uL_sVZh6<07km9M;g!%Ef'
        'jVE5i%Gh2r(#II(v5V+21cu@VLax=c(+Gij7YxfVCTGIf_PB%PQjI<H#U2MyJDzX?K~uRLPk5o#@q`&x-kP&a{<Sn|nIS+U^h#hv'
        '3?WQ$>Lx6!j0v6XA?&#hUwU~Xrq~AF(b;7#ueRPd@U_hxb&v$1R=H6iQKM!DcqVk^8mk4!Mw9dFArn*vB3(xgaI8PLp^mRn*X4e7'
        '$OxFxuEri7xG|_jgoF}5>)A@~QDkG22ooS($;LJwx5j-#ZCuc8vzRdS#z33hlZ0)D)Nl2X)!2^g7Rx4Uu_t-xaZ};T@Ffa+)p`yM'
        '#zRu22)nnE@27P4QNG+FuAm-aLIi?f>)G4zhzvZ8gO6EF^bD>TZ5_@+1Ma}La2LLVd+<H%z(aTt!%7oAT!oLIG7DGX8mz)~HPP-@'
        '7{YdsQU_d<uwK{dXBB+WG#`Vn;G32+K)~*1sM=lGsjQv69QdY&{5{jJjwIPfmTJ=x_ec9B`RK3zPfG_vLpQix$$`NC2#sT86gVt0'
        '(n~14)RT6M2gGgT8z{XoY&;-t8}FcWXV`c^+%|rS(x=151LC&vGn76XHtrWEB?CDeO>ZTG?JN@TE|PBt9{hV+!jG^EP53EAI4oGU'
        'jU1A?@=Tq=#+*!KL4Z*gf09{kshQ8Pj;lU%KTg_z-=u?iOiB?-l`%6*U}+b<-jm4bMBhr*ey6wear@PE>Q~u13z_7jn%k|U=bXk3'
        'X{_v{R@81+GM!LXvPPbH6t!ZSgx?V9`LMFnqkML!d%0-!0BV8_f553|WL(v>>COXHz560n{d*t3pZBF7$0H8k5a&B<CnI&E8Fi&g'
        '?9GklrT&{tYV(;<*C8B9``m?)3scJhc1Y?Ea$pQOP==*u`ZAG<-qwk+OlE5eAA81d4L*T&*l3N!|I{1PBp5S<>I5~5LCp@-lsXXH'
        '>T@n<oI5zmxukIZeDR!aokpnrJvg~%_PR++Ut+UpKGDAL4-c)sP@5Iqq^D-q)<tuw3+7QUk2!qA|9HM;0%83PXSC`hs0;uA'
    )
    assert isinstance(_MODEL_, _pydsdl_.ServiceType)
